/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=writer.wrangler.jsonc --env=test --include-runtime=false --env-interface=WriterEnv writer/worker-env.d.ts` (hash: 927f9581c5071611f3fdb2a315fedf79)
interface __BaseEnv_WriterEnv {
	SKILL_REGISTRY_BUCKET: R2Bucket;
	REGISTRY_WRITER: DurableObjectNamespace<import("./src/index").RegistryWriter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RegistryWriter";
	}
	interface Env extends __BaseEnv_WriterEnv {}
}
interface WriterEnv extends __BaseEnv_WriterEnv {}
